name: projekt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Added for internationalization
    sdk: flutter         # Added for internationalization
  provider: ^6.1.2      # Added for state management
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2 # Added for authentication

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # Added for generating launcher icons

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo.png" # Corrected path to the logo file

flutter:
  uses-material-design: true
  generate: true # Added for internationalization

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bitburger.jpg
    - assets/pulleken.png # Corrected a typo here
